before_install:
- brew update
install:
- brew install hugo
script: scripts/build.sh
deploy: scripts/deploy.sh
notifications:
  slack:
    rooms: 
      - PTl0hea72Z2Nkj/v7fNC/CiPrsj5z4Nm3V+cCZ7TeeoNlWFqHTQOF7ceI77jdH39W18JE+umZPyanzI+LIbmDC36OkNwOTWyt/o8Yh65ft33ugVSUdewlRX1kZL+4JMBbHCEpl0hAp5Bm14q0JAqNC9Oc1p7nEFd/0S1NlYRBYgj5WcD6vFwQlFIF3xO/NDDMz1ByJbJHhp64lhLiz3CJ7/2VnRye2WQFbGLVepDsCENSW4OEecOV/+OjI3jAws5iPH4VPbc9/q0ZE0qGDzUv61Bz2JIffUA8LHkOsx+Snap7xJsMI2ovcCre/rzRjTFti707mGAeGKFwmj6z3gkb5NCy466A9x6PwgZ/WJ/0OrsGnQ8Nwp7EeeSWC3K7E6jAD/wJtZdQpBtasRqmKc6FX5IwtAHmLe015xSXN/oUCaa6XxlwBrXkq74T9qHKjAhzz96tnsPBdX9/BwhwDuN0SQSZ43Oqbnd/tgb/jiymKXJoqmijkXmrsC6S7R/ZmoltMglVBl3MnfwIYOWwPOJX+/ppjdsMeptrqN4TgrQ7wdGBVVM2t1DNlYKyvHquWZpcJFxv3Jm2LzxuwwVszFTfa6+0nptOTZC6AWIewEPDw5807WF/81aSwujC1M2cnQT6QaYHIA7Zqtrh5nOd3eSX1styxblk5Cv3EKtd1r6yGU=
    on_success: always
    on_failure: always
