baseurl: "https://nativewheel.house/"
languageCode: "en-us"
title: "Native Wheelhouse"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
canonifyurls: true
metadataformat: "yaml"
theme: "hugo-material-docs"

params:
 # General information
 author: "Digitalcraftsman"
 description: "A material design theme for documentations."
 copyright: "Released under the MIT license"

 # Repository
 provider: "GitHub"
 repo_url: "https://github.com/NativeWheelhouse"

 version: "1.0.0"
 logo: "images/logo.png"
 favicon: ""

 permalink: "#"

 # Custom assets
 custom_css: []
 custom_js: []

 # Syntax highlighting theme
 highlight_css: ""

 params:
  palette:
   - primary: "red"
     accent: "light green"

 params:
  font:
   - text: "Ubuntu"
     code: "Ubuntu Mono"

social:
 twitter: "nwhcast"
 github: "NativeWheelhouse"

menu:
 main:
  - name: "NWH Home"
    url: "/"
    weight: 0
  - name: "Episodes"
    identifier: "episode"
    url: "/episodes/"
    weight: 10
  - name: "The Nerds"
    url: "about-us/"
    weight: 20